export const routeImages = {
  'Les Lacets de Montvernier':   '/routes/montvernier.jpg',
  'Le Col de la Croix de Fer':   '/routes/croix-de-fer.jpg',
  'Les Chemins du Beaujolais':   '/routes/beaujolais.jpg',
  'Le Mont Ventoux par Bédoin':  '/routes/ventoux.jpg',
  'La Corniche des Maures':      '/routes/corniche-maures.jpg',
  'Les Ocres du Luberon':        '/routes/luberon.jpg',
  'La Vallée de Chevreuse':      '/routes/chevreuse.jpg',
  'Les Boucles de la Seine':     '/routes/boucles-seine.jpg',
  'La Forêt de Fontainebleau':   '/routes/fontainebleau.jpg',
  'La Côte de Granit Rose':      '/routes/granit-rose.jpg',
  "La Presqu'île de Crozon":     '/routes/crozon.jpg',
  'Les Landes de Monteneuf':     '/routes/monteneuf.jpg',
  'Le Col du Tourmalet':         '/routes/tourmalet.jpg',
  "Les Gorges de l'Hérault":    '/routes/herault.jpg',
  'Le Plateau du Larzac':        '/routes/larzac.jpg',
  'Les Vignobles du Médoc':      '/routes/medoc.jpg',
  'La Vélodyssée Atlantique':    '/routes/velodyssee.jpg',
  'Les Pistes des Landes':       '/routes/landes.jpg',
};
